modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="ceetweaks"
version="1.0.0"
displayName="CEE Tweaks"
authors="YourNameHere, OtherNameHere"
description='''Example mod description.
Newline characters can be used and will be replaced properly.'''

[[mixins]]
config="ceetweaks.mixins.json"

[[dependencies.ceetweaks]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.174,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ceetweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ceetweaks]]
    modId="electroenergetics"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ceetweaks]]
    modId="immersiveengineering"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
